name: Deploy to Azure
on:
  workflow_call:
    inputs:
      ENVIRONMENT_NAME:
        required: true
        type: string

jobs:
  deploy-to-azure:
    runs-on: [self-hosted, azure]
    environment:
      name: ${{ inputs.ENVIRONMENT_NAME }}

    steps:
      - name: Get repository name as lower case string
        id: string
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: "ghcr.io/${{ steps.string.outputs.lowercase }}/${{ inputs.ENVIRONMENT_NAME }}:azure-latest"
