name: Workflow Test

on:
  push:
    branches:
      - test

  workflow_dispatch:

jobs:
  deploy-test:
    uses: ./.github/workflows/build-and-deploy-container.yml
    with:
      ENVIRONMENT_NAME: test
    secrets: inherit
