name: Workflow Dev

on:
  push:
    branches:
      - dev

  workflow_dispatch:

jobs:
  build-azure:
    uses: ./.github/workflows/build-image.yml
    with:
      ENVIRONMENT_NAME: development
      REDIRECT_URL: https://front-wework-dev.azurewebsites.net/
      API_URL: https://app-wework-dev.azurewebsites.net
      TAG: azure
    secrets: inherit

  build-aws:
    uses: ./.github/workflows/build-image.yml
    with:
      ENVIRONMENT_NAME: development
      REDIRECT_URL: https://cubical.dev.digital.idf.il/
      API_URL: https://cubical.dev.digital.idf.il
      TAG: aws
    secrets: inherit

  deploy-azure:
    needs: build-azure
    uses: ./.github/workflows/deploy-azure.yml
    with:
      ENVIRONMENT_NAME: development
    secrets: inherit
